name: Infra and Deploy

on:
  push:
    branches: [ master ]


permissions:
  id-token: write   
  contents: read    

jobs:
  terraform-config:
    runs-on: ubuntu-latest
    outputs:
      s3_bucket: ${{ steps.set-outputs.outputs.s3_bucket }}
      distribution_id: ${{ steps.set-outputs.outputs.distribution_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::785867473499:role/roleForOIDC
          aws-region: eu-north-1
          
      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Set Outputs
        id: set-outputs
        run: |
          echo "s3_bucket=$(terraform output -raw s3_bucket)" >> $GITHUB_OUTPUT
          echo "distribution_id=$(terraform output -raw distribution_id)" >> $GITHUB_OUTPUT

  build-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.16'
          cache: 'npm'
          cache-dependency-path: './front_touragency/package-lock.json'

      - name: Build
        run: |
          cd ./front_touragency/
          npm install
          CI=false npm run build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: front-build
          path: ./front_touragency/build/

  deploy-to-s3:
    runs-on: ubuntu-latest
    needs: [terraform-config, build-front]
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: front-build
          path: ./build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::785867473499:role/roleForOIDC
          aws-region: eu-north-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://${{ needs.terraform-config.outputs.s3_bucket }}/ --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ needs.terraform-config.outputs.distribution_id }} \
            --paths '/*'
